version: '3'
services:
  db:
    container_name: 'app_pg'
    image: 'postgres:12.6'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "$USER"
      POSTGRES_HOST_AUTH_METHOD: "trust"
  redis:
    container_name: 'app_redis'
    image: "redis:4.0"
    ports:
      - 6379:6379